version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  postgres:
    image: postgres
    env_file:
      - .env
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_PORT: ${POSTGRES_PORT}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/volumes/redis:/data


  app:
    image: service:latest
    ports:
      - 5000:5000
    command: [ "python", "main.py" ]
