version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - my_network

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/volumes/redis:/data
    networks:
      - my_network

  app:
    image: service:latest
    ports:
      - 5000:5000
    command: [ "python", "main.py" ]
    networks:
      - my_network

networks:
  my_network:
